### ISSUE TITLE
958 commits behind ODK Collect

### ISSUE THREAD

**Issue by davereinhart** [kobotoolbox/collect#7]
Are there any plans to update KoboCollect to keep it up to date with ODK Collect?  A number of bug fixes and new features have been added:

[https://github.com/opendatakit/collect/releases](https://github.com/opendatakit/collect/releases)

Thanks!

**Comment by tinok** [comment]
Yes! It is on our list, stay tuned!

**Comment by lognaturel** [comment]
How about pointing users to the ODK Collect core? It seems that would be the most helpful for users to get support, bug fixes, new features, etc.

**Comment by pmusaraj** [comment]
Hi @lognaturel, 
I updated KoboCollect on April 19, 2018, which brought us up to date with ODK Collect version 1.14.0. 
Thanks for the ping though, this helps clean up our issue tracker here.
